from redis import Redis

from app.models.room import Room


class RoomRepository:
	def __init__(self, redis_client: Redis) -> None: ...

	def create_room(self, room: Room) -> Room: ...

	def get_room(self, room_code: str) -> Room | None: ...

	def list_public_rooms(self) -> list[Room]: ...

	def save_room(self, room: Room) -> Room: ...

	def delete_room(self, room_code: str) -> bool: ...

	def expire_room(self, room_code: str) -> bool: ...
